const planetDatabase = [
    {
        "Atmosphere": "Likely none",
        "Composition": "Rocky",
        "Day Length (days)": 1.51,
        "description": "TRAPPIST-1b is the innermost planet in the TRAPPIST-1 system, orbiting its host star in just 1.5 days. Sitting extremely close to the ultra-cool red dwarf, it receives intense radiation and reaches scorching surface temperatures. It's likely tidally locked, with one side in permanent daylight. Observations suggest it's a bare, rocky world with little to no atmosphere.",
        "Diameter (km)": 14220,
        "Gravity (Earth)": 1.1,
        "Habitability": "Low",
        "Mass (Earths)": 1.374,
        "Planet": "TRAPPIST-1b",
        "Planet Type": "Terrestrial",
        "Radius (Earths)": 1.116,
        "Temperature (K)": 398,
        "Water": "Unknown",
        "Wind Speed": "Unknown",
        "Year Length (days)": 1.51
    },
    {
        "Atmosphere": "Possibly very thin",
        "Composition": "Rocky",
        "Day Length (days)": 2.42,
        "Diameter (km)": 13970,
        "Gravity (Earth)": 1.09,
        "Habitability": "Low",
        "Mass (Earths)": 1.308,
        "Planet": "TRAPPIST-1c",
        "Planet Type": "Terrestrial",
        "Radius (Earths)": 1.097,
        "Temperature (K)": 340,
        "Water": "Unknown",
        "Wind Speed": "Unknown",
        "Year Length (days)": 2.42
    },
    {
        "Atmosphere": "Unknown",
        "Composition": "Rocky / possible volatiles",
        "Day Length (days)": 4.05,
        "Diameter (km)": 9810,
        "Gravity (Earth)": 0.65,
        "Habitability": "Possible",
        "Mass (Earths)": 0.388,
        "Planet": "TRAPPIST-1d",
        "Planet Type": "Terrestrial",
        "Radius (Earths)": 0.77,
        "Temperature (K)": 286,
        "Water": "Unknown",
        "Wind Speed": "Unknown",
        "Year Length (days)": 4.05
    },
    {
        "Atmosphere": "Unknown",
        "Composition": "Rocky",
        "Day Length (days)": 6.1,
        "Diameter (km)": 11730,
        "Gravity (Earth)": 0.82,
        "Habitability": "Best candidate",
        "Mass (Earths)": 0.692,
        "Planet": "TRAPPIST-1e",
        "Planet Type": "Terrestrial",
        "Radius (Earths)": 0.92,
        "Temperature (K)": 250,
        "Water": "Possible",
        "Wind Speed": "Unknown",
        "Year Length (days)": 6.1
    },
    {
        "Atmosphere": "Unknown",
        "Composition": "Rocky / possible ice",
        "Day Length (days)": 9.21,
        "Diameter (km)": 13320,
        "Gravity (Earth)": 0.95,
        "Habitability": "Possible",
        "Mass (Earths)": 1.039,
        "Planet": "TRAPPIST-1f",
        "Planet Type": "Terrestrial",
        "Radius (Earths)": 1.045,
        "Temperature (K)": 218,
        "Water": "Possible",
        "Wind Speed": "Unknown",
        "Year Length (days)": 9.21
    },
    {
        "Atmosphere": "Unknown",
        "Composition": "Rocky / possible ice",
        "Day Length (days)": 12.35,
        "Diameter (km)": 14380,
        "Gravity (Earth)": 1.04,
        "Habitability": "Possible",
        "Mass (Earths)": 1.321,
        "Planet": "TRAPPIST-1g",
        "Planet Type": "Terrestrial",
        "Radius (Earths)": 1.129,
        "Temperature (K)": 197,
        "Water": "Possible",
        "Wind Speed": "Unknown",
        "Year Length (days)": 12.35
    },
    {
        "Atmosphere": "Unknown",
        "Composition": "Rocky / possible ice",
        "Day Length (days)": 18.77,
        "Diameter (km)": 9620,
        "Gravity (Earth)": 0.57,
        "Habitability": "Low",
        "Mass (Earths)": 0.326,
        "Planet": "TRAPPIST-1h",
        "Planet Type": "Terrestrial",
        "Radius (Earths)": 0.755,
        "Temperature (K)": 172,
        "Water": "Possible ice",
        "Wind Speed": "Unknown",
        "Year Length (days)": 18.77
    },
    {
        "Atmosphere": "Likely none",
        "Composition": "Plasma",
        "Day Length (days)": null,
        "Diameter (km)": 169000,
        "Gravity (Earth)": 5.24,
        "Habitability": "Inhabitable",
        "Mass (Earths)": 29870.0,
        "Planet": "SPECULOOS-1",
        "Planet Type": "Dwarf Star",
        "Radius (Earths)": 13.02,
        "Temperature (K)": 2566,
        "Water": "Impossible",
        "Wind Speed": "Unknown",
        "Year Length (days)": null
    }
];